[package]
name = "erebus"
description = "Easily transpile into a bad interpreted language of your choice."

version.workspace = true
edition.workspace = true

[workspace]
members = ["erebus_mir", "erebus_parser"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
chumsky = "=1.0.0-alpha.8"
ariadne = "0.5.1"

[dependencies]
erebus_mir = { path = "./erebus_mir" }
erebus_parser = { path = "./erebus_parser" }

clap = { version = "4.5.17", features = ["derive"] }
chumsky.workspace = true
ariadne.workspace = true
